CREATE TABLE `t_store` (
	`S_Id` VARCHAR(20) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`S_Loc` VARCHAR(20) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`S_IsLease` BIT(1)  DEFAULT b'0' NOT NULL,
	`S_Name` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`S_Rent` INT(10) NULL DEFAULT NULL,
	`S_Master` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`S_Pa` VARCHAR(20) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	PRIMARY KEY (`S_Id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
